spring:
  application:
    name: iorange-web
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
  main:
    banner-mode: off
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
server:
  port: 8088
  context-path: /iorange

